FROM python:3.7-alpine

LABEL maintainer "Koh Meng Wang <mengwangk@gmail.com>"

ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV=prod

COPY Pipfile Pipfile.lock ./

RUN apk update && \
    apk add --virtual build-deps gcc musl-dev && \
    apk add postgresql-dev && \
    rm -rf /var/cache/apk/*

# delete dependencies required to install certain python packages 
# to make the docker image smaller
RUN apk del build-deps gcc musl-dev && pip uninstall -y pipenv

RUN pip install pipenv
RUN pipenv install --system

RUN mkdir /app
COPY . /app
WORKDIR /app

EXPOSE 5000

# ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:5000", "--log-level", "INFO", "manage:app" ]