version: '3.7'

networks:
  dev_network:
    driver: bridge
    
services:
  db:
    container_name: db
    restart: always
    networks:
      - dev_network
    image: postgres
    env_file:
      - .env
    volumes:
      - app-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    container_name: app
    restart: always
    networks:
      - dev_network
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: flask run --host=0.0.0.0 -p 5000 --reload --debugger
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    # entrypoint:
    #  - /app/docker_script.sh

volumes:
  app-db:
    name: app-db