version: '3'

networks:
  dev_network:
    driver: bridge
    
services:
  db:
    restart: always
    networks:
      - dev_network
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  app:
    restart: always
    networks:
      - dev_network
    build: .
    env_file:
      - .env
    command: flask run --host=0.0.0.0 -p 5000 --reload --debugger
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db