version: '3'

networks:
  dev_network:
    driver: s
    ss
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - FLASK_APP=manage.py
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db