version: '3'

networks:
  dev_network:
    driver: bridge
    
services:
  db:
    networks:
      - dev_network
    image: postgres
    env_file:
      - .env
    expose:
      - 5432

  app:
    networks:
      - dev_network
    build: .
    env_file:
      - .env
    #environment:
    #  - FLASK_APP=manage.py
    command: flask run --host=0.0.0.0 -p 5000 --reload --debugger
    volumes:
      - .:/code
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db