version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - FLASK_APP=manage.py
    command: flask run
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db